insert into users (name, school_email, vouchers_points, password) values ('Clayborne Burker', 'e0069944@u.nus.edu', 300, 'J6VOUpvLvJzJ');
insert into users (name, school_email, vouchers_points, password) values ('Leda Dyos', 'e0983308@u.nus.edu',1100, 'ZDQrvWw');
insert into users (name, school_email, vouchers_points, password) values ('Maressa Merryman', 'e0079294@u.nus.edu', 1500, 'J5Z96raxK');
insert into users (name, school_email, vouchers_points, password) values ('Cloe Longford', 'e0155362@u.nus.edu',1000, '6EnsRp9');
insert into users (name, school_email, vouchers_points, password) values ('Adolph Hallgalley', 'e0132083@u.nus.edu',  500, 'UmaKNfplHCVp');
insert into users (name, school_email, vouchers_points, password) values ('Tedi Headland', 'e0553515@u.nus.edu', 400, '05ibOdvigr');
insert into users (name, school_email, vouchers_points, password) values ('Aluin Kempston', 'e0510916@u.nus.edu',  300, 'TqYE6iFx7uA');
insert into users (name, school_email, vouchers_points, password) values ('Elora Jimmison', 'e0578458@u.nus.edu',  1500, 'atUfxl');
insert into users (name, school_email, vouchers_points, password) values ('Gates Hobben', 'e0316035@u.nus.edu',  1000, 'bZTjzQ');
insert into users (name, school_email, vouchers_points, password) values ('Winnie Lindner', 'e0660702@u.nus.edu',  600, '7ZY0s7DmLkR');
insert into users (name, school_email, vouchers_points, password) values ('Jordan Digger', 'e0700183@u.nus.edu',  1400, 'SFklpACDl');
insert into users (name, school_email, vouchers_points, password) values ('Victoria Wemyss', 'e0342695@u.nus.edu',  1300, 'TaETpa');
insert into users (name, school_email,  vouchers_points, password) values ('Gaylene Kenney', 'e0631895@u.nus.edu',  1000, 'c7rNf7wK6TiA');
insert into users (name, school_email,  vouchers_points, password) values ('Gabey Maywood', 'e0868980@u.nus.edu',  1000, 'LHWAbrMA');
insert into users (name, school_email,  vouchers_points, password) values ('Viola Halse', 'e0441861@u.nus.edu',  700, 'xVidiu9aVidz');
insert into users (name, school_email,  vouchers_points, password) values ('Artemis Kail', 'e0230088@u.nus.edu',  1400, 'fEmWEfS3pD');
insert into users (name, school_email,  vouchers_points, password) values ('Alexandr Crannage', 'e0599007@u.nus.edu',  100, 'bA6ggyG');
insert into users (name, school_email,  vouchers_points, password) values ('Joyce Boecke', 'e0916636@u.nus.edu',  1300, 'VPDIYge0kqlM');
insert into users (name, school_email,  vouchers_points, password) values ('Holmes Ponte', 'e0555975@u.nus.edu',  1000, 'D52ix6');
insert into users (name, school_email,  vouchers_points, password) values ('Sybil Cassell', 'e0367216@u.nus.edu',  500, 'pNL2F13s');
insert into users (name, school_email,  vouchers_points, password) values ('Thedric Staples', 'e0413060@u.nus.edu',  500, 'YkI8Rrs');
insert into users (name, school_email,  vouchers_points, password) values ('Dunstan Conwell', 'e0803605@u.nus.edu',  1300, 'j1lkW5NY68');
insert into users (name, school_email,  vouchers_points, password) values ('Tootsie Naughton', 'e0495075@u.nus.edu',  500, '5eiA6nFJMuhc');
insert into users (name, school_email,  vouchers_points, password) values ('Carver Amber', 'e0171795@u.nus.edu',  300, '4BNhGtFqo');
insert into users (name, school_email,  vouchers_points, password) values ('Lowell Killingsworth', 'e0187952@u.nus.edu',  1400, 'ZGEsGFt');
insert into users (name, school_email, vouchers_points, password) values ('Nappy Ricardin', 'e0014242@u.nus.edu',  700, 'TC4Bar');
insert into users (name, school_email,  vouchers_points, password) values ('Yetta Eyree', 'e0805690@u.nus.edu',  1200, 'AoKrcC');
insert into users (name, school_email, vouchers_points, password) values ('Felic Borrel', 'e0007531@u.nus.edu',  200, 'fG2TORdyV2R');
insert into users (name, school_email,  vouchers_points, password) values ('Reilly Ruecastle', 'e0068480@u.nus.edu',  500, 'Xw2tAY476V');
insert into users (name, school_email,  vouchers_points, password) values ('Doy Stebbing', 'e0135116@u.nus.edu',  0, 'V09gjSERmA');
insert into users (name, school_email,  vouchers_points, password) values ('Kerk Sandlin', 'e0728475@u.nus.edu',  1200, '5nytzM9');
insert into users (name, school_email,  vouchers_points, password) values ('Hilde Patey', 'e0980654@u.nus.edu',  300, 'xMcDmLu');
insert into users (name, school_email,  vouchers_points, password) values ('Lucian Wield', 'e0291724@u.nus.edu',  300, 'MukcRdvrGu');
insert into users (name, school_email, vouchers_points, password) values ('Felic Thurske', 'e0953392@u.nus.edu',  200, 'yO9E3ThuZVYF');
insert into users (name, school_email,  vouchers_points, password) values ('Minnaminnie Iannini', 'e0802861@u.nus.edu',  1500, 'mW1YFHvbA');
insert into users (name, school_email,  vouchers_points, password) values ('Elsie Caulier', 'e0241394@u.nus.edu',  800, 'u1FQRiAzXuh');
insert into users (name, school_email, vouchers_points, password) values ('Freddy Alpine', 'e0244494@u.nus.edu',  400, 'wotPFJQuBU');
insert into users (name, school_email,  vouchers_points, password) values ('Hadria Coskerry', 'e0109281@u.nus.edu',  600, 'flPU5QwCWuO');
insert into users (name, school_email, vouchers_points, password) values ('Witty Templar', 'e0844932@u.nus.edu',  600, 'EUOlNM');
insert into users (name, school_email,  vouchers_points, password) values ('Dyanna Rodge', 'e0314540@u.nus.edu',  900, 'R3LgO5');
insert into users (name, school_email, vouchers_points, password) values ('Britteny Elliston', 'e0741080@u.nus.edu',  600, 'vskg1rHWJjaM');
insert into users (name, school_email,  vouchers_points, password) values ('Filmore Kinnoch', 'e0718505@u.nus.edu',  1500, '9CLW2pU');
insert into users (name, school_email,  vouchers_points, password) values ('Clary Advani', 'e0468656@u.nus.edu',  600, 'in4qQ0');
insert into users (name, school_email,  vouchers_points, password) values ('Nissa La Padula', 'e0647063@u.nus.edu', 1400, 'aPuEoh');
insert into users (name, school_email,  vouchers_points, password) values ('Cordelie Jirik', 'e0714124@u.nus.edu',  0, 'LNswMuflloUJ');
insert into users (name, school_email,  vouchers_points, password) values ('Roxanna Woodburn', 'e0456597@u.nus.edu', 1000, 'ljgikWLjkJ');
insert into users (name, school_email,  vouchers_points, password) values ('Tull Jannasch', 'e0218129@u.nus.edu',  400, '7wB3vYk8vjQ');
insert into users (name, school_email,  vouchers_points, password) values ('Aviva Masser', 'e0252895@u.nus.edu',  100, 'AzXfELs5UYD');
insert into users (name, school_email, vouchers_points, password) values ('Rebeka Radnage', 'e0389672@u.nus.edu',  400, 'qzcPruSTbTGu');
insert into users (name, school_email,  vouchers_points, password) values ('Shermy Ogelsby', 'e0316233@u.nus.edu',  1400, 'Iaao9bQdgR');
insert into users (name, school_email,  vouchers_points, password) values ('Danie Berger', 'e0999785@u.nus.edu',  1000, 'wup5p3');
insert into users (name, school_email,  vouchers_points, password) values ('Leia Keems', 'e0977384@u.nus.edu',  1100, 'tkcRCf7');
insert into users (name, school_email,  vouchers_points, password) values ('Jeffie Belderfield', 'e0903682@u.nus.edu',  400, 'GF8Uv2csZ');
insert into users (name, school_email, vouchers_points, password) values ('Hansiain Vallentin', 'e0598875@u.nus.edu',  1400, 'I8PyCclo7');
insert into users (name, school_email,  vouchers_points, password) values ('Tris Dunston', 'e0815501@u.nus.edu',  600, 'uf0xrBAQ');
insert into users (name, school_email, vouchers_points, password) values ('Tawnya Keppel', 'e0221766@u.nus.edu', 700, 'wQvoAbUXY');
insert into users (name, school_email,  vouchers_points, password) values ('Grier Zotto', 'e0579578@u.nus.edu',  1000, '2t2X6lJ9');
insert into users (name, school_email,  vouchers_points, password) values ('Betty Priddey', 'e0522948@u.nus.edu',  1100, 'v5FR3YQ39kEf');
insert into users (name, school_email, vouchers_points, password) values ('Cleve Bachshell', 'e0731310@u.nus.edu',  900, 'NXY1ACP');
insert into users (name, school_email,  vouchers_points, password) values ('Keefe Reiglar', 'e0716316@u.nus.edu',  800, 'xr0Wcq71');
insert into users (name, school_email, vouchers_points, password) values ('Liza Lagden', 'e0281901@u.nus.edu',  1400, 'q8YKpBmx');
insert into users (name, school_email,vouchers_points, password) values ('Margi Kalaher', 'e0611699@u.nus.edu',  800, 'p7joHa7');
insert into users (name, school_email, vouchers_points, password) values ('Ivor Maulin', 'e0220705@u.nus.edu',  800, '9if7Hd');
insert into users (name, school_email,  vouchers_points, password) values ('Julianna Laxon', 'e0894129@u.nus.edu', 600, 'B8GDG2');
insert into users (name, school_email,  vouchers_points, password) values ('Leelah Millmoe', 'e0144077@u.nus.edu',  1400, '3amH6I');
insert into users (name, school_email,  vouchers_points, password) values ('Mort Blaksley', 'e0593227@u.nus.edu',  300, 'hzjySxN');
insert into users (name, school_email,  vouchers_points, password) values ('Farleigh Ribeiro', 'e0635762@u.nus.edu',  1200, 'u3y4Uy5oX5HH');
insert into users (name, school_email,  vouchers_points, password) values ('Che Tubridy', 'e0182665@u.nus.edu',  800, 'iN3h48FKiPaQ');
insert into users (name, school_email,  vouchers_points, password) values ('Catlaina Lain', 'e0276879@u.nus.edu',  700, 'dD0yBRkCl');
insert into users (name, school_email, vouchers_points, password) values ('Benoite Matuszewski', 'e0137290@u.nus.edu',  100, 'yyKWKqqBG1kE');
insert into users (name, school_email,  vouchers_points, password) values ('Daniela Hallwell', 'e0860024@u.nus.edu',  100, 'tAy29tF');
insert into users (name, school_email, vouchers_points, password) values ('Lethia McCray', 'e0059880@u.nus.edu',  1500, 'BYJbcpoaW');
insert into users (name, school_email,  vouchers_points, password) values ('Tremaine Gudgion', 'e0411132@u.nus.edu',  1400, 'LQeCNIcJR');
insert into users (name, school_email, vouchers_points, password) values ('Karleen Gilliland', 'e0987768@u.nus.edu',  0, 'XDm0xIYDIVpJ');
insert into users (name, school_email,  vouchers_points, password) values ('Talbert Macconachy', 'e0951388@u.nus.edu',  1100, 'NqolEIeu1Rw');
insert into users (name, school_email,  vouchers_points, password) values ('Dell Finlayson', 'e0859893@u.nus.edu',  600, 'IqdliOYdVe');
insert into users (name, school_email, vouchers_points, password) values ('Orville Darnborough', 'e0285026@u.nus.edu',  700, 'ttPxwYr7');
insert into users (name, school_email,  vouchers_points, password) values ('Samara De Minico', 'e0343515@u.nus.edu',  200, '8neET0exsNT');
insert into users (name, school_email,  vouchers_points, password) values ('Thane Seaward', 'e0877160@u.nus.edu',  1400, '9KZYcLbQ');
insert into users (name, school_email, vouchers_points, password) values ('Marillin Look', 'e0369941@u.nus.edu',  1500, 'l1uCc31irzU');
insert into users (name, school_email, vouchers_points, password) values ('Emmalynne Shewsmith', 'e0083527@u.nus.edu', 1200, 'GJo4jN1pZfv');
insert into users (name, school_email, vouchers_points, password) values ('Rockwell Thexton', 'e0728241@u.nus.edu',  100, 'zdLGxbcbR7E');
insert into users (name, school_email, vouchers_points, password) values ('Renata Baudain', 'e0923330@u.nus.edu',  1100, 'VD244gs94GM');
insert into users (name, school_email,  vouchers_points, password) values ('Maurine Clayworth', 'e0646363@u.nus.edu',  1300, 'jMdhVn');
insert into users (name, school_email,  vouchers_points, password) values ('Merci Thursby', 'e0970377@u.nus.edu',  700, 'EdbVd5hKwSE');
insert into users (name, school_email, vouchers_points, password) values ('Alejoa Nattrass', 'e0847967@u.nus.edu',  1200, 'KoMMlNcvEIFk');
insert into users (name, school_email,  vouchers_points, password) values ('Mark Denecamp', 'e0515213@u.nus.edu',  0, 'zhFpIIzBb');
insert into users (name, school_email,  demerit_points, vouchers_points, password) values ('Jasen Ingolotti', 'e0368990@u.nus.edu',  3, 100, '0WcPfaYyEu');
insert into users (name, school_email,  demerit_points, vouchers_points, password) values ('Cathrin Swinerd', 'e0284592@u.nus.edu',  1, 1200, 'dMi0VaQS0B');
insert into users (name, school_email,  demerit_points, vouchers_points, password) values ('Valli Wythill', 'e0180095@u.nus.edu',  7, 1200, 'X6PyuF2');
insert into users (name, school_email,  demerit_points, vouchers_points, password) values ('Adolph Erdely', 'e0653508@u.nus.edu',  6, 800, 'jclSng1Ouo0');
insert into users (name, school_email, demerit_points, vouchers_points, password) values ('Harmonia Tomblings', 'e0651888@u.nus.edu',  6, 200, 'FdBkN8DS');
insert into users (name, school_email,  demerit_points, vouchers_points, password) values ('Bailey Dafforne', 'e0564917@u.nus.edu',  6, 200, 'cPMpXb');
insert into users (name, school_email,  demerit_points, vouchers_points, password, suspend) values ('Ulrich Tattersdill', 'e0019988@u.nus.edu',  14, 700, 'z2R9dvTYcu', true);
insert into users (name, school_email, demerit_points, vouchers_points, password, suspend) values ('Gregory Barnshaw', 'e0002783@u.nus.edu',  15, 900, 'YBIjMODzv', true);
insert into users (name, school_email, demerit_points, vouchers_points, password, suspend) values ('Karleen McLeese', 'e0166073@u.nus.edu',  8, 800, '6RLLnJUT', true);
