INSERT INTO vouch VALUES('Gong Cha $5', 'Gong Cha', 5, 500);
INSERT INTO vouch VALUES('Koi $5', 'Koi', 5, 500);
INSERT INTO vouch VALUES('Hwangs Free Gyoza', 'Hwangs', 3.80, 400); 
INSERT INTO vouch VALUES('Arise & Shine $2', 'Arise & Shine', 2, 200);
INSERT INTO vouch VALUES('Bar Bar Black Sheep $20', 'Bar Bar Black Sheep', 20, 2000);
INSERT INTO vouch VALUES('Bistro Box $3.50', 'Bistro Box', 3.50, 350);
INSERT INTO vouch VALUES('Central Square $1', 'Central Square', 1, 100);
INSERT INTO vouch VALUES('Flash Coffee 1 for 1', 'Flash Coffee', 6, 600);
INSERT INTO vouch VALUES('Flash Coffee $2', 'Flash Coffee', 2, 200);
INSERT INTO vouch VALUES('Maxx Coffee $2', 'Maxx Coffee', 2, 200);
INSERT INTO vouch VALUES('Nine Fresh $1', 'Nine Fresh', 1, 100);
INSERT INTO vouch VALUES('Pasta Express $2', 'Pasta Express', 2, 200);
INSERT INTO vouch VALUES('Spinelli Free Muffin', 'Spinelli', 4.50, 400);
INSERT INTO vouch VALUES('Supersnacks Free Ice Cream', 'Supersnacks', 1, 100);
INSERT INTO vouch VALUES('Supersnacks $2', 'Supersnacks', 2, 200);
INSERT INTO vouch VALUES('Taiwan Ichiban Free Honey Chicken', 'Taiwan Ichiban', 4.80, 500);
INSERT INTO vouch VALUES('Techno Edge $1', 'Techno Edge', 1, 100);
INSERT INTO vouch VALUES('The Deck $1', 'The Deck', 1, 100);
INSERT INTO vouch VALUES('The Tea Party Free Brownie','The Tea Party', 2, 200);
INSERT INTO vouch VALUES('Uncle Penyet Fusion $2','Uncle Penyet', 2, 200);
INSERT INTO vouch VALUES('Maxx Coffee $10','Maxx Coffee', 10, 1000);
INSERT INTO vouch VALUES('Pasta Express $1', 'Pasta Express', 1,100);
INSERT INTO vouch VALUES('Central Square Free Takoyaki', 'Central Square', 5, 500);
INSERT INTO vouch VALUES('Central Square $2', 'Central Square', 2, 200);
