insert into users (name, school_email, current_borrowed_items, voucher_points, password) values ('Sigmund Chazette', 'e7513377@u.nus.edu', 1, 1500, 'aoLJHF5');
insert into users (name, school_email, current_borrowed_items, voucher_points, password) values ('Saunderson Burkitt', 'e5334330@u.nus.edu', 2, 1000, 'qsB2SS');
insert into users (name, school_email, current_borrowed_items, voucher_points, password) values ('Agnese Ibel', 'e1352108@u.nus.edu', 1, 1300, 'Ic09Z43GpDC3');
insert into users (name, school_email, current_borrowed_items, voucher_points, password) values ('Kilian Hanhard', 'e1712857@u.nus.edu', 2, 700, 'ecbQ6PZqWQP');
insert into users (name, school_email, current_borrowed_items, voucher_points, password) values ('Cleavland Francescoccio', 'e5954526@u.nus.edu', 1, 700, 'ESxWOV0uru');
insert into users (name, school_email, current_borrowed_items, voucher_points, password) values ('Joelle Skypp', 'e1060540@u.nus.edu', 2, 1100, 'wMxJYYMR');
insert into users (name, school_email, current_borrowed_items, voucher_points, password) values ('Cristal Clampton', 'e3837267@u.nus.edu', 2, 500, 'KHy6msSH3i');
insert into users (name, school_email, current_borrowed_items, voucher_points, password) values ('Adriena Rableau', 'e4794606@u.nus.edu', 0, 300, 'jV4C0co9E4vU');
insert into users (name, school_email, current_borrowed_items, voucher_points, password) values ('Mignon Depka', 'e1041533@u.nus.edu', 0, 500, '7IwYCJ9');
insert into users (name, school_email, current_borrowed_items, voucher_points, password) values ('Goldarina Di Franceschi', 'e7352490@u.nus.edu', 2, 800, 'P9D0cCxt');
insert into users (name, school_email, current_borrowed_items, voucher_points, password) values ('Lisabeth Sincock', 'e5180902@u.nus.edu', 1, 600, 'd6mWDggZg');
insert into users (name, school_email, current_borrowed_items, voucher_points, password) values ('Ailey Stolworthy', 'e8666783@u.nus.edu', 0, 400, 'am9DMEwSJRCP');
insert into users (name, school_email, current_borrowed_items, voucher_points, password) values ('Jake Clapshaw', 'e5747563@u.nus.edu', 1, 300, '6PUZNBKjycpJ');
insert into users (name, school_email, current_borrowed_items, voucher_points, password) values ('Marie Birch', 'e1915728@u.nus.edu', 2, 1300, '9BFsJcv');
insert into users (name, school_email, current_borrowed_items, voucher_points, password) values ('Reinaldo Brodway', 'e9196326@u.nus.edu', 2, 1100, '289W2VMBVq5U');
insert into users (name, school_email, current_borrowed_items, voucher_points, password) values ('Sloan Fratson', 'e0870164@u.nus.edu', 1, 1200, 'V2B34BSpB22l');
insert into users (name, school_email, current_borrowed_items, voucher_points, password) values ('Cammi Spanswick', 'e9629035@u.nus.edu', 2, 1100, 'p1HHEV');
insert into users (name, school_email, current_borrowed_items, voucher_points, password) values ('Gerri Francis', 'e2858628@u.nus.edu', 2, 900, 'e0B2o2');
insert into users (name, school_email, current_borrowed_items, voucher_points, password) values ('Carolina Tiptaft', 'e6392749@u.nus.edu', 1, 700, '1sQ6xsh1b4');
insert into users (name, school_email, current_borrowed_items, voucher_points, password) values ('Salomo Corran', 'e6301583@u.nus.edu', 2, 900, 'qYFnpB');
insert into users (name, school_email, current_borrowed_items, voucher_points, password) values ('Puff Birchenhead', 'e2494753@u.nus.edu', 1, 400, 'ikizKdzO');
insert into users (name, school_email, current_borrowed_items, voucher_points, password) values ('Allard Ickovic', 'e5476745@u.nus.edu', 1, 1100, 'qkx7iAGXY0');
insert into users (name, school_email, current_borrowed_items, voucher_points, password) values ('Aridatha Gecke', 'e8894698@u.nus.edu', 2, 1400, 'ofVsi688WCiN');
insert into users (name, school_email, current_borrowed_items, voucher_points, password) values ('Patrick Boule', 'e4981796@u.nus.edu', 1, 100, 'eBPQ15w');
insert into users (name, school_email, current_borrowed_items, voucher_points, password) values ('Dottie Dade', 'e0822562@u.nus.edu', 2, 1000, 'jArHkf1zZ7');
insert into users (name, school_email, current_borrowed_items, voucher_points, password) values ('Gasparo Broseke', 'e8190278@u.nus.edu', 1, 600, 'TW4t3kZ1C');
insert into users (name, school_email, current_borrowed_items, voucher_points, password) values ('Jacob Gideon', 'e8259601@u.nus.edu', 1, 500, 'eKfYyoO3wl');
insert into users (name, school_email, current_borrowed_items, voucher_points, password) values ('Uri Curtiss', 'e1734601@u.nus.edu', 2, 600, 'gbwMUfYiI7Q');
insert into users (name, school_email, current_borrowed_items, voucher_points, password) values ('Karen Longforth', 'e1205324@u.nus.edu', 2, 800, 'GrlMlR');
insert into users (name, school_email, current_borrowed_items, voucher_points, password) values ('Constantine Del Monte', 'e2318752@u.nus.edu', 2, 1100, 'r67EAuzLr7');
insert into users (name, school_email, current_borrowed_items, voucher_points, password) values ('Christie Limeburner', 'e2264550@u.nus.edu', 2, 500, 't5TfVCXNPy');
insert into users (name, school_email, current_borrowed_items, voucher_points, password) values ('Robbert Teal', 'e6624630@u.nus.edu', 0, 1400, '86TvDRVmDJ');
insert into users (name, school_email, current_borrowed_items, voucher_points, password) values ('Deerdre Daintree', 'e5487244@u.nus.edu', 2, 1500, 'c9cPewJy');
insert into users (name, school_email, current_borrowed_items, voucher_points, password) values ('Rooney Jales', 'e0831813@u.nus.edu', 1, 300, 'GtOa1Q7');
insert into users (name, school_email, current_borrowed_items, voucher_points, password) values ('Royall Bigby', 'e1385506@u.nus.edu', 0, 1300, 'eNGLQrpD');
insert into users (name, school_email, current_borrowed_items, voucher_points, password) values ('Leshia Dodamead', 'e9944055@u.nus.edu', 2, 600, 'SeU5XZdjJq');
insert into users (name, school_email, current_borrowed_items, voucher_points, password) values ('Clevie Balle', 'e3065274@u.nus.edu', 2, 1300, 'y17Aw0');
insert into users (name, school_email, current_borrowed_items, voucher_points, password) values ('Jeniffer Birchill', 'e4813764@u.nus.edu', 2, 1300, 'O1By71');
insert into users (name, school_email, current_borrowed_items, voucher_points, password) values ('Jacinta Giovannoni', 'e4858227@u.nus.edu', 0, 1100, 'H3tbBZesys');
insert into users (name, school_email, current_borrowed_items, voucher_points, password) values ('Amaleta Lemarie', 'e0082849@u.nus.edu', 0, 900, '6STeia3ofd');
insert into users (name, school_email, current_borrowed_items, voucher_points, password) values ('Hillier Talbot', 'e6218127@u.nus.edu', 0, 900, 'oW1qM3CsskNi');
insert into users (name, school_email, current_borrowed_items, voucher_points, password) values ('Myrna Manssuer', 'e3077887@u.nus.edu', 1, 1400, '1iHzun5R');
insert into users (name, school_email, current_borrowed_items, voucher_points, password) values ('Bil Chudleigh', 'e8607756@u.nus.edu', 0, 200, '69R7GzHN2bo');
insert into users (name, school_email, current_borrowed_items, voucher_points, password) values ('Judi Itzkov', 'e8600282@u.nus.edu', 1, 700, 'GHkYA8');
insert into users (name, school_email, current_borrowed_items, voucher_points, password) values ('Bailey Brightman', 'e0012246@u.nus.edu', 2, 700, 'eXwqvmT9fPyT');
insert into users (name, school_email, current_borrowed_items, voucher_points, password) values ('Rhett Robrow', 'e0455325@u.nus.edu', 2, 100, '5noATYogW');
insert into users (name, school_email, current_borrowed_items, voucher_points, password) values ('Yvette Kaplin', 'e2770471@u.nus.edu', 2, 600, 'R7oDsUfWpfo');
insert into users (name, school_email, current_borrowed_items, voucher_points, password) values ('Leora Gillyett', 'e8792786@u.nus.edu', 0, 800, 'H6QXW8l8');
insert into users (name, school_email, current_borrowed_items, voucher_points, password) values ('Cull Bilbee', 'e0932641@u.nus.edu', 2, 1500, 'NYH9nIyBfB');
insert into users (name, school_email, current_borrowed_items, voucher_points, password) values ('Kelly Maynell', 'e1596756@u.nus.edu', 0, 0, 'NHkjHzqJBUg');
insert into users (name, school_email, current_borrowed_items, voucher_points, password) values ('Trev Ivermee', 'e6061756@u.nus.edu', 2, 1300, 'p5YP8isn');
insert into users (name, school_email, current_borrowed_items, voucher_points, password) values ('Marylynne Mannock', 'e0966743@u.nus.edu', 1, 400, 'T8nVHM');
insert into users (name, school_email, current_borrowed_items, voucher_points, password) values ('Rancell Cattow', 'e8032790@u.nus.edu', 1, 0, '3zenzU8v');
insert into users (name, school_email, current_borrowed_items, voucher_points, password) values ('Hester Piquard', 'e5766910@u.nus.edu', 2, 900, 'jEWAQCrVieqB');
insert into users (name, school_email, current_borrowed_items, voucher_points, password) values ('Robbi Franzke', 'e2951586@u.nus.edu', 0, 1000, 's6OKqb4goP');
insert into users (name, school_email, current_borrowed_items, voucher_points, password) values ('Ruperto Mc Caughan', 'e9446208@u.nus.edu', 1, 1500, '16JrnH');
insert into users (name, school_email, current_borrowed_items, voucher_points, password) values ('Lennie Sussans', 'e7956555@u.nus.edu', 0, 1400, 'F87nizZ');
insert into users (name, school_email, current_borrowed_items, voucher_points, password) values ('Elisha Champ', 'e5074714@u.nus.edu', 0, 200, 'gE3N6wdX');
insert into users (name, school_email, current_borrowed_items, voucher_points, password) values ('Skipper Estevez', 'e8366894@u.nus.edu', 1, 1000, 'Fr7HyEEmHW7');
insert into users (name, school_email, current_borrowed_items, voucher_points, password) values ('Alfy Aldersley', 'e1803824@u.nus.edu', 1, 1200, 'V0wcHoaxSPQ');
insert into users (name, school_email, current_borrowed_items, voucher_points, password) values ('Stirling Lubomirski', 'e9535128@u.nus.edu', 0, 200, 'QdWtwKQ');
insert into users (name, school_email, current_borrowed_items, voucher_points, password) values ('Rainer Coughtrey', 'e9968759@u.nus.edu', 0, 1200, '3iNlATnNuCy');
insert into users (name, school_email, current_borrowed_items, voucher_points, password) values ('Salem Settle', 'e5763858@u.nus.edu', 2, 1200, 'tZAUjO9Am');
insert into users (name, school_email, current_borrowed_items, voucher_points, password) values ('Evaleen Birkbeck', 'e9092109@u.nus.edu', 2, 0, 'OqGmVirr');
insert into users (name, school_email, current_borrowed_items, voucher_points, password) values ('Timothea Mulcock', 'e9867713@u.nus.edu', 0, 300, 'TAcVh4JOV8S');
insert into users (name, school_email, current_borrowed_items, voucher_points, password) values ('Courtney Schustl', 'e4659979@u.nus.edu', 0, 900, 's97zBWhysou');
insert into users (name, school_email, current_borrowed_items, voucher_points, password) values ('Hoebart Doughtery', 'e4433051@u.nus.edu', 1, 1200, '48Hdhhzq65P');
insert into users (name, school_email, current_borrowed_items, voucher_points, password) values ('Teirtza Perutto', 'e7187755@u.nus.edu', 2, 1300, 'fsxSm38W');
insert into users (name, school_email, current_borrowed_items, voucher_points, password) values ('Darya Skep', 'e4071534@u.nus.edu', 1, 200, 'V6GTHDGJvMpl');
insert into users (name, school_email, current_borrowed_items, voucher_points, password) values ('Reilly Goodger', 'e7072463@u.nus.edu', 0, 0, 'RTGip0zjF26e');
insert into users (name, school_email, current_borrowed_items, voucher_points, password) values ('Roberto Studdal', 'e1481685@u.nus.edu', 1, 1000, 'qz70QVe');
insert into users (name, school_email, current_borrowed_items, voucher_points, password) values ('Magnum Solman', 'e2092934@u.nus.edu', 1, 1400, 'pq05nqDYQ2W');
insert into users (name, school_email, current_borrowed_items, voucher_points, password) values ('Adelina Brunner', 'e0957946@u.nus.edu', 1, 1500, 'QHtLsW4Qe');
insert into users (name, school_email, current_borrowed_items, voucher_points, password) values ('Charmion Oake', 'e5286031@u.nus.edu', 0, 1500, 'Dopa0v');
insert into users (name, school_email, current_borrowed_items, voucher_points, password) values ('Roseann Tapper', 'e0778534@u.nus.edu', 1, 1200, '0arZNt5m0BC3');
insert into users (name, school_email, current_borrowed_items, voucher_points, password) values ('Rutger Stoodley', 'e4007100@u.nus.edu', 1, 100, 'eJ0iPlMgSr');
insert into users (name, school_email, current_borrowed_items, voucher_points, password) values ('Suellen Kelmere', 'e2790021@u.nus.edu', 1, 500, 'J7alGc');
insert into users (name, school_email, current_borrowed_items, voucher_points, password) values ('Wenona Sellwood', 'e6535906@u.nus.edu', 0, 200, 'Cu3Ue2K');
insert into users (name, school_email, current_borrowed_items, voucher_points, password) values ('Kirstyn Trickett', 'e2814956@u.nus.edu', 2, 400, '8mJgmKGc');
insert into users (name, school_email, current_borrowed_items, voucher_points, password) values ('Beverly Humburton', 'e1141208@u.nus.edu', 1, 1000, 'kpeU16eo');
insert into users (name, school_email, current_borrowed_items, voucher_points, password) values ('Curr Volage', 'e1084134@u.nus.edu', 1, 1200, 'ZTOBzT');
insert into users (name, school_email, current_borrowed_items, voucher_points, password) values ('Renata Flieg', 'e7054221@u.nus.edu', 1, 1500, 'a7ct5U');
insert into users (name, school_email, current_borrowed_items, voucher_points, password) values ('Leopold Brigshaw', 'e6866952@u.nus.edu', 1, 0, 'e3bzXn0GR5');
insert into users (name, school_email, current_borrowed_items, voucher_points, password) values ('Raphaela Boycott', 'e8347102@u.nus.edu', 2, 800, 'bmx0A8XNLb');
insert into users (name, school_email, current_borrowed_items, voucher_points, password) values ('Padriac McGeachy', 'e2830905@u.nus.edu', 0, 1000, 'ZPoDQtUhJ');
insert into users (name, school_email, current_borrowed_items, voucher_points, password) values ('Broderic Belch', 'e9271954@u.nus.edu', 2, 0, 'jEyGCb');
insert into users (name, school_email, current_borrowed_items, voucher_points, password) values ('Hasty Diggell', 'e7723386@u.nus.edu', 2, 1300, 'uYmtX7fOkd');
insert into users (name, school_email, current_borrowed_items, demerit_points, voucher_points, password) values ('Jasen Ingolotti', 'e0368990@u.nus.edu', 2, 3, 100, '0WcPfaYyEu');
insert into users (name, school_email, current_borrowed_items, demerit_points, voucher_points, password) values ('Cathrin Swinerd', 'e0284592@u.nus.edu', 2, 1, 1200, 'dMi0VaQS0B');
insert into users (name, school_email, current_borrowed_items, demerit_points, voucher_points, password) values ('Valli Wythill', 'e0180095@u.nus.edu', 2, 7, 1200, 'X6PyuF2');
insert into users (name, school_email, current_borrowed_items, demerit_points, voucher_points, password) values ('Adolph Erdely', 'e0653508@u.nus.edu', 1, 6, 800, 'jclSng1Ouo0');
insert into users (name, school_email, current_borrowed_items, demerit_points, voucher_points, password) values ('Harmonia Tomblings', 'e0651888@u.nus.edu', 2, 6, 200, 'FdBkN8DS');
insert into users (name, school_email, current_borrowed_items, demerit_points, voucher_points, password) values ('Bailey Dafforne', 'e0564917@u.nus.edu', 2, 6, 200, 'cPMpXb');
insert into users (name, school_email, current_borrowed_items, demerit_points, voucher_points, password, suspend) values ('Ulrich Tattersdill', 'e0019988@u.nus.edu', 2, 14, 700, 'z2R9dvTYcu', true);
insert into users (name, school_email, current_borrowed_items, demerit_points, voucher_points, password, suspend) values ('Gregory Barnshaw', 'e0002783@u.nus.edu', 2, 15, 900, 'YBIjMODzv', true);
insert into users (name, school_email, current_borrowed_items, demerit_points, voucher_points, password, suspend) values ('Karleen McLeese', 'e0166073@u.nus.edu', 2, 8, 800, '6RLLnJUT', true);
